if(NOT DEFINED NOMAD_DISTRIBUTION_OUTPUT)
    set(NOMAD_DISTRIBUTION_OUTPUT "${CMAKE_CURRENT_LIST_DIR}")
endif()
get_filename_component(NOMAD_DISTRIBUTION_OUTPUT "${NOMAD_DISTRIBUTION_OUTPUT}" ABSOLUTE)
if(NOT DEFINED NOMAD_TEST_ROOT)
    set(NOMAD_TEST_ROOT "${NOMAD_DISTRIBUTION_OUTPUT}/smoke-test")
endif()
if(EXISTS "${NOMAD_TEST_ROOT}")
    message(FATAL_ERROR "Distribution smoke test requires a new directory: ${NOMAD_TEST_ROOT}")
endif()

file(STRINGS "${NOMAD_DISTRIBUTION_OUTPUT}/SHA256SUMS.txt" CHECKSUMS)
list(LENGTH CHECKSUMS CHECKSUM_COUNT)
if(NOT CHECKSUM_COUNT EQUAL 2)
    message(FATAL_ERROR "Expected SDK and runtime checksums")
endif()
foreach(LINE IN LISTS CHECKSUMS)
    if(NOT LINE MATCHES "^([0-9a-f]+)  (nomad-(sdk|runtime)-[a-z0-9-]+-[0-9.]+\\.zip)$")
        message(FATAL_ERROR "Invalid checksum entry: ${LINE}")
    endif()
    set(EXPECTED "${CMAKE_MATCH_1}")
    set(NAME "${CMAKE_MATCH_2}")
    set(KIND "${CMAKE_MATCH_3}")
    file(SHA256 "${NOMAD_DISTRIBUTION_OUTPUT}/${NAME}" ACTUAL)
    if(NOT EXPECTED STREQUAL ACTUAL)
        message(FATAL_ERROR "Checksum mismatch for ${NAME}")
    endif()
    if(DEFINED ARCHIVE_${KIND})
        message(FATAL_ERROR "Duplicate ${KIND} archive")
    endif()
    set(ARCHIVE_${KIND} "${NOMAD_DISTRIBUTION_OUTPUT}/${NAME}")
endforeach()
if(NOT DEFINED ARCHIVE_sdk OR NOT DEFINED ARCHIVE_runtime)
    message(FATAL_ERROR "SDK and runtime archives are both required")
endif()
set(SDK "${NOMAD_TEST_ROOT}/SDK with spaces")
set(BUNDLE "${NOMAD_TEST_ROOT}/runtime")
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE_sdk}" DESTINATION "${SDK}")
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE_runtime}" DESTINATION "${BUNDLE}")
file(READ "${BUNDLE}/runtime.json" MANIFEST)
string(JSON VERSION GET "${MANIFEST}" version)
string(JSON FILE_COUNT LENGTH "${MANIFEST}" files)
math(EXPR LAST_FILE "${FILE_COUNT} - 1")
foreach(INDEX RANGE ${LAST_FILE})
    string(JSON PATH GET "${MANIFEST}" files ${INDEX} path)
    file(SHA256 "${BUNDLE}/${PATH}" RUNTIME_CHECKSUM)
    file(SHA256 "${SDK}/runtime/${PATH}" SDK_CHECKSUM)
    if(NOT SDK_CHECKSUM STREQUAL RUNTIME_CHECKSUM)
        message(FATAL_ERROR "SDK and runtime bundles differ: ${PATH}")
    endif()
endforeach()

if(CMAKE_HOST_WIN32)
    set(SUFFIX ".exe")
    set(ENV{PATH} "$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
else()
    set(SUFFIX "")
    set(ENV{PATH} "/usr/bin:/bin")
endif()
unset(ENV{LD_LIBRARY_PATH})
unset(ENV{LD_PRELOAD})
unset(ENV{DYLD_LIBRARY_PATH})
unset(ENV{DYLD_FALLBACK_LIBRARY_PATH})

function(run_success)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${NOMAD_TEST_ROOT}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR_OUTPUT TIMEOUT 30)
    if(NOT RESULT STREQUAL "0")
        message(FATAL_ERROR "Command failed (${RESULT}): ${ARGV}\n${OUTPUT}\n${ERROR_OUTPUT}")
    endif()
endfunction()

foreach(PROGRAM IN ITEMS nomad nomadc)
    execute_process(COMMAND "${SDK}/${PROGRAM}${SUFFIX}" --version
        WORKING_DIRECTORY "${NOMAD_TEST_ROOT}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR_OUTPUT TIMEOUT 30)
    string(STRIP "${OUTPUT}" OUTPUT)
    string(FIND "${OUTPUT}" "${VERSION}" VERSION_POSITION)
    if(NOT RESULT STREQUAL "0" OR VERSION_POSITION LESS 0)
        message(FATAL_ERROR "Extracted ${PROGRAM} version failed: ${RESULT}\n${OUTPUT}\n${ERROR_OUTPUT}")
    endif()
endforeach()
set(PROJECT "${NOMAD_TEST_ROOT}/game")
run_success("${SDK}/nomad${SUFFIX}" init "${PROJECT}")
run_success("${SDK}/nomad${SUFFIX}" check "${PROJECT}")
run_success("${SDK}/nomad${SUFFIX}" package "${PROJECT}")
run_success("${SDK}/nomad-runtime${SUFFIX}" --help)
string(JSON RUNTIME_NAME GET "${MANIFEST}" files 0 path)
run_success("${BUNDLE}/${RUNTIME_NAME}" --help)
message(STATUS "Extracted SDK initializes, checks, and packages a game; runtime bundle starts")
file(REMOVE_RECURSE "${NOMAD_TEST_ROOT}")
