if(NOT DEFINED NOMAD_DISTRIBUTION_OUTPUT)
    set(NOMAD_DISTRIBUTION_OUTPUT "${CMAKE_CURRENT_LIST_DIR}")
endif()
get_filename_component(NOMAD_DISTRIBUTION_OUTPUT "${NOMAD_DISTRIBUTION_OUTPUT}" ABSOLUTE)
if(NOT DEFINED NOMAD_TEST_ROOT)
    set(NOMAD_TEST_ROOT "${NOMAD_DISTRIBUTION_OUTPUT}/smoke-test")
endif()
if(EXISTS "${NOMAD_TEST_ROOT}")
    message(FATAL_ERROR "Distribution smoke test requires a new directory: ${NOMAD_TEST_ROOT}")
endif()

file(STRINGS "${NOMAD_DISTRIBUTION_OUTPUT}/SHA256SUMS.txt" CHECKSUMS)
list(LENGTH CHECKSUMS CHECKSUM_COUNT)
if(NOT CHECKSUM_COUNT EQUAL 1)
    message(FATAL_ERROR "Expected exactly one SDK checksum")
endif()
list(GET CHECKSUMS 0 LINE)
if(NOT LINE MATCHES "^([0-9a-f]+)  (nomad-sdk-[a-z0-9-]+-[0-9.]+\\.zip)$")
    message(FATAL_ERROR "Invalid checksum entry: ${LINE}")
endif()
set(EXPECTED "${CMAKE_MATCH_1}")
set(NAME "${CMAKE_MATCH_2}")
file(SHA256 "${NOMAD_DISTRIBUTION_OUTPUT}/${NAME}" ACTUAL)
if(NOT EXPECTED STREQUAL ACTUAL)
    message(FATAL_ERROR "Checksum mismatch for ${NAME}")
endif()
set(SDK "${NOMAD_TEST_ROOT}/SDK with spaces")
set(BUNDLE "${SDK}/runtime")
file(ARCHIVE_EXTRACT INPUT "${NOMAD_DISTRIBUTION_OUTPUT}/${NAME}" DESTINATION "${SDK}")
file(READ "${BUNDLE}/runtime.json" MANIFEST)
string(JSON VERSION GET "${MANIFEST}" version)
string(JSON FILE_COUNT LENGTH "${MANIFEST}" files)
math(EXPR LAST_FILE "${FILE_COUNT} - 1")
foreach(INDEX RANGE ${LAST_FILE})
    string(JSON PATH GET "${MANIFEST}" files ${INDEX} path)
    if(NOT EXISTS "${BUNDLE}/${PATH}")
        message(FATAL_ERROR "Missing declared runtime bundle file: ${PATH}")
    endif()
endforeach()

if(CMAKE_HOST_WIN32)
    set(SUFFIX ".exe")
    set(ENV{PATH} "$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
else()
    set(SUFFIX "")
    set(ENV{PATH} "/usr/bin:/bin")
endif()
unset(ENV{LD_LIBRARY_PATH})
unset(ENV{LD_PRELOAD})
unset(ENV{DYLD_LIBRARY_PATH})
unset(ENV{DYLD_FALLBACK_LIBRARY_PATH})

function(run_success)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${NOMAD_TEST_ROOT}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR_OUTPUT TIMEOUT 30)
    if(NOT RESULT STREQUAL "0")
        message(FATAL_ERROR "Command failed (${RESULT}): ${ARGV}\n${OUTPUT}\n${ERROR_OUTPUT}")
    endif()
endfunction()

foreach(PROGRAM IN ITEMS nomad nomadc)
    execute_process(COMMAND "${SDK}/${PROGRAM}${SUFFIX}" --version
        WORKING_DIRECTORY "${NOMAD_TEST_ROOT}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR_OUTPUT TIMEOUT 30)
    string(STRIP "${OUTPUT}" OUTPUT)
    string(FIND "${OUTPUT}" "${VERSION}" VERSION_POSITION)
    if(NOT RESULT STREQUAL "0" OR VERSION_POSITION LESS 0)
        message(FATAL_ERROR "Extracted ${PROGRAM} version failed: ${RESULT}\n${OUTPUT}\n${ERROR_OUTPUT}")
    endif()
endforeach()
set(PROJECT "${NOMAD_TEST_ROOT}/game")
run_success("${SDK}/nomad${SUFFIX}" init "${PROJECT}")
run_success("${SDK}/nomad${SUFFIX}" check "${PROJECT}")
run_success("${SDK}/nomad${SUFFIX}" package "${PROJECT}")
run_success("${SDK}/nomad-runtime${SUFFIX}" --help)
string(JSON RUNTIME_NAME GET "${MANIFEST}" files 0 path)
run_success("${BUNDLE}/${RUNTIME_NAME}" --help)
message(STATUS "Extracted SDK initializes, checks, and packages a game using its included runtime")
file(REMOVE_RECURSE "${NOMAD_TEST_ROOT}")
