// Copyright (c) 2023-2026 Jean-François Bilodeau (@jfbilodeau).

// Input code constants in this file are adapted from SDL.
// Copyright (C) 1997-2025 Sam Lantinga <slouken@libsdl.org>
//
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented; you must not
//    claim that you wrote the original software. If you use this software
//    in a product, an acknowledgment in the product documentation would be
//    appreciated but is not required.
// 2. Altered source versions must be plainly marked as such, and must not be
//    misrepresented as being the original software.
// 3. This notice may not be removed or altered from any source distribution.

#pragma once

#include <nomad/Nomad.hpp>

#include <SDL3/SDL_events.h>

namespace nomad {

// Forward declarations
class Game;

using InputCode = NomadId;

// Nomad input mapping.
constexpr InputCode INPUT_CODE_NONE = -1;
constexpr InputCode INPUT_KEYBOARD_OFFSET = 0;
constexpr InputCode INPUT_MOUSE_OFFSET = 1000;
constexpr InputCode INPUT_CONTROLLER1_OFFSET = 2000;

// Based on SDL2's SDL_scancode.h
// https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_scancode.h
constexpr InputCode INPUT_SCANCODE_UNKNOWN = INPUT_KEYBOARD_OFFSET + 0;
constexpr InputCode INPUT_SCANCODE_A = INPUT_KEYBOARD_OFFSET + 4;
constexpr InputCode INPUT_SCANCODE_B = INPUT_KEYBOARD_OFFSET + 5;
constexpr InputCode INPUT_SCANCODE_C = INPUT_KEYBOARD_OFFSET + 6;
constexpr InputCode INPUT_SCANCODE_D = INPUT_KEYBOARD_OFFSET + 7;
constexpr InputCode INPUT_SCANCODE_E = INPUT_KEYBOARD_OFFSET + 8;
constexpr InputCode INPUT_SCANCODE_F = INPUT_KEYBOARD_OFFSET + 9;
constexpr InputCode INPUT_SCANCODE_G = INPUT_KEYBOARD_OFFSET + 10;
constexpr InputCode INPUT_SCANCODE_H = INPUT_KEYBOARD_OFFSET + 11;
constexpr InputCode INPUT_SCANCODE_I = INPUT_KEYBOARD_OFFSET + 12;
constexpr InputCode INPUT_SCANCODE_J = INPUT_KEYBOARD_OFFSET + 13;
constexpr InputCode INPUT_SCANCODE_K = INPUT_KEYBOARD_OFFSET + 14;
constexpr InputCode INPUT_SCANCODE_L = INPUT_KEYBOARD_OFFSET + 15;
constexpr InputCode INPUT_SCANCODE_M = INPUT_KEYBOARD_OFFSET + 16;
constexpr InputCode INPUT_SCANCODE_N = INPUT_KEYBOARD_OFFSET + 17;
constexpr InputCode INPUT_SCANCODE_O = INPUT_KEYBOARD_OFFSET + 18;
constexpr InputCode INPUT_SCANCODE_P = INPUT_KEYBOARD_OFFSET + 19;
constexpr InputCode INPUT_SCANCODE_Q = INPUT_KEYBOARD_OFFSET + 20;
constexpr InputCode INPUT_SCANCODE_R = INPUT_KEYBOARD_OFFSET + 21;
constexpr InputCode INPUT_SCANCODE_S = INPUT_KEYBOARD_OFFSET + 22;
constexpr InputCode INPUT_SCANCODE_T = INPUT_KEYBOARD_OFFSET + 23;
constexpr InputCode INPUT_SCANCODE_U = INPUT_KEYBOARD_OFFSET + 24;
constexpr InputCode INPUT_SCANCODE_V = INPUT_KEYBOARD_OFFSET + 25;
constexpr InputCode INPUT_SCANCODE_W = INPUT_KEYBOARD_OFFSET + 26;
constexpr InputCode INPUT_SCANCODE_X = INPUT_KEYBOARD_OFFSET + 27;
constexpr InputCode INPUT_SCANCODE_Y = INPUT_KEYBOARD_OFFSET + 28;
constexpr InputCode INPUT_SCANCODE_Z = INPUT_KEYBOARD_OFFSET + 29;
constexpr InputCode INPUT_SCANCODE_1 = INPUT_KEYBOARD_OFFSET + 30;
constexpr InputCode INPUT_SCANCODE_2 = INPUT_KEYBOARD_OFFSET + 31;
constexpr InputCode INPUT_SCANCODE_3 = INPUT_KEYBOARD_OFFSET + 32;
constexpr InputCode INPUT_SCANCODE_4 = INPUT_KEYBOARD_OFFSET + 33;
constexpr InputCode INPUT_SCANCODE_5 = INPUT_KEYBOARD_OFFSET + 34;
constexpr InputCode INPUT_SCANCODE_6 = INPUT_KEYBOARD_OFFSET + 35;
constexpr InputCode INPUT_SCANCODE_7 = INPUT_KEYBOARD_OFFSET + 36;
constexpr InputCode INPUT_SCANCODE_8 = INPUT_KEYBOARD_OFFSET + 37;
constexpr InputCode INPUT_SCANCODE_9 = INPUT_KEYBOARD_OFFSET + 38;
constexpr InputCode INPUT_SCANCODE_0 = INPUT_KEYBOARD_OFFSET + 39;
constexpr InputCode INPUT_SCANCODE_RETURN = INPUT_KEYBOARD_OFFSET + 40;
constexpr InputCode INPUT_SCANCODE_ESCAPE = INPUT_KEYBOARD_OFFSET + 41;
constexpr InputCode INPUT_SCANCODE_BACKSPACE = INPUT_KEYBOARD_OFFSET + 42;
constexpr InputCode INPUT_SCANCODE_TAB = INPUT_KEYBOARD_OFFSET + 43;
constexpr InputCode INPUT_SCANCODE_SPACE = INPUT_KEYBOARD_OFFSET + 44;
constexpr InputCode INPUT_SCANCODE_MINUS = INPUT_KEYBOARD_OFFSET + 45;
constexpr InputCode INPUT_SCANCODE_EQUALS = INPUT_KEYBOARD_OFFSET + 46;
constexpr InputCode INPUT_SCANCODE_LEFTBRACKET = INPUT_KEYBOARD_OFFSET + 47;
constexpr InputCode INPUT_SCANCODE_RIGHTBRACKET = INPUT_KEYBOARD_OFFSET + 48;
constexpr InputCode INPUT_SCANCODE_BACKSLASH = INPUT_KEYBOARD_OFFSET + 49;
constexpr InputCode INPUT_SCANCODE_NONUSHASH = INPUT_KEYBOARD_OFFSET + 50;
constexpr InputCode INPUT_SCANCODE_SEMICOLON = INPUT_KEYBOARD_OFFSET + 51;
constexpr InputCode INPUT_SCANCODE_APOSTROPHE = INPUT_KEYBOARD_OFFSET + 52;
constexpr InputCode INPUT_SCANCODE_GRAVE = INPUT_KEYBOARD_OFFSET + 53;
constexpr InputCode INPUT_SCANCODE_COMMA = INPUT_KEYBOARD_OFFSET + 54;
constexpr InputCode INPUT_SCANCODE_PERIOD = INPUT_KEYBOARD_OFFSET + 55;
constexpr InputCode INPUT_SCANCODE_SLASH = INPUT_KEYBOARD_OFFSET + 56;
constexpr InputCode INPUT_SCANCODE_CAPSLOCK = INPUT_KEYBOARD_OFFSET + 57;
constexpr InputCode INPUT_SCANCODE_F1 = INPUT_KEYBOARD_OFFSET + 58;
constexpr InputCode INPUT_SCANCODE_F2 = INPUT_KEYBOARD_OFFSET + 59;
constexpr InputCode INPUT_SCANCODE_F3 = INPUT_KEYBOARD_OFFSET + 60;
constexpr InputCode INPUT_SCANCODE_F4 = INPUT_KEYBOARD_OFFSET + 61;
constexpr InputCode INPUT_SCANCODE_F5 = INPUT_KEYBOARD_OFFSET + 62;
constexpr InputCode INPUT_SCANCODE_F6 = INPUT_KEYBOARD_OFFSET + 63;
constexpr InputCode INPUT_SCANCODE_F7 = INPUT_KEYBOARD_OFFSET + 64;
constexpr InputCode INPUT_SCANCODE_F8 = INPUT_KEYBOARD_OFFSET + 65;
constexpr InputCode INPUT_SCANCODE_F9 = INPUT_KEYBOARD_OFFSET + 66;
constexpr InputCode INPUT_SCANCODE_F10 = INPUT_KEYBOARD_OFFSET + 67;
constexpr InputCode INPUT_SCANCODE_F11 = INPUT_KEYBOARD_OFFSET + 68;
constexpr InputCode INPUT_SCANCODE_F12 = INPUT_KEYBOARD_OFFSET + 69;
constexpr InputCode INPUT_SCANCODE_PRINTSCREEN = INPUT_KEYBOARD_OFFSET + 70;
constexpr InputCode INPUT_SCANCODE_SCROLLLOCK = INPUT_KEYBOARD_OFFSET + 71;
constexpr InputCode INPUT_SCANCODE_PAUSE = INPUT_KEYBOARD_OFFSET + 72;
constexpr InputCode INPUT_SCANCODE_INSERT = INPUT_KEYBOARD_OFFSET + 73;
constexpr InputCode INPUT_SCANCODE_HOME = INPUT_KEYBOARD_OFFSET + 74;
constexpr InputCode INPUT_SCANCODE_PAGEUP = INPUT_KEYBOARD_OFFSET + 75;
constexpr InputCode INPUT_SCANCODE_DELETE = INPUT_KEYBOARD_OFFSET + 76;
constexpr InputCode INPUT_SCANCODE_END = INPUT_KEYBOARD_OFFSET + 77;
constexpr InputCode INPUT_SCANCODE_PAGEDOWN = INPUT_KEYBOARD_OFFSET + 78;
constexpr InputCode INPUT_SCANCODE_RIGHT = INPUT_KEYBOARD_OFFSET + 79;
constexpr InputCode INPUT_SCANCODE_LEFT = INPUT_KEYBOARD_OFFSET + 80;
constexpr InputCode INPUT_SCANCODE_DOWN = INPUT_KEYBOARD_OFFSET + 81;
constexpr InputCode INPUT_SCANCODE_UP = INPUT_KEYBOARD_OFFSET + 82;
constexpr InputCode INPUT_SCANCODE_NUMLOCKCLEAR = INPUT_KEYBOARD_OFFSET + 83;
constexpr InputCode INPUT_SCANCODE_KP_DIVIDE = INPUT_KEYBOARD_OFFSET + 84;
constexpr InputCode INPUT_SCANCODE_KP_MULTIPLY = INPUT_KEYBOARD_OFFSET + 85;
constexpr InputCode INPUT_SCANCODE_KP_MINUS = INPUT_KEYBOARD_OFFSET + 86;
constexpr InputCode INPUT_SCANCODE_KP_PLUS = INPUT_KEYBOARD_OFFSET + 87;
constexpr InputCode INPUT_SCANCODE_KP_ENTER = INPUT_KEYBOARD_OFFSET + 88;
constexpr InputCode INPUT_SCANCODE_KP_1 = INPUT_KEYBOARD_OFFSET + 89;
constexpr InputCode INPUT_SCANCODE_KP_2 = INPUT_KEYBOARD_OFFSET + 90;
constexpr InputCode INPUT_SCANCODE_KP_3 = INPUT_KEYBOARD_OFFSET + 91;
constexpr InputCode INPUT_SCANCODE_KP_4 = INPUT_KEYBOARD_OFFSET + 92;
constexpr InputCode INPUT_SCANCODE_KP_5 = INPUT_KEYBOARD_OFFSET + 93;
constexpr InputCode INPUT_SCANCODE_KP_6 = INPUT_KEYBOARD_OFFSET + 94;
constexpr InputCode INPUT_SCANCODE_KP_7 = INPUT_KEYBOARD_OFFSET + 95;
constexpr InputCode INPUT_SCANCODE_KP_8 = INPUT_KEYBOARD_OFFSET + 96;
constexpr InputCode INPUT_SCANCODE_KP_9 = INPUT_KEYBOARD_OFFSET + 97;
constexpr InputCode INPUT_SCANCODE_KP_0 = INPUT_KEYBOARD_OFFSET + 98;
constexpr InputCode INPUT_SCANCODE_KP_PERIOD = INPUT_KEYBOARD_OFFSET + 99;
constexpr InputCode INPUT_SCANCODE_NONUSBACKSLASH = INPUT_KEYBOARD_OFFSET + 100;
constexpr InputCode INPUT_SCANCODE_APPLICATION = INPUT_KEYBOARD_OFFSET + 101;
constexpr InputCode INPUT_SCANCODE_POWER = INPUT_KEYBOARD_OFFSET + 102;
constexpr InputCode INPUT_SCANCODE_KP_EQUALS = INPUT_KEYBOARD_OFFSET + 103;
constexpr InputCode INPUT_SCANCODE_F13 = INPUT_KEYBOARD_OFFSET + 104;
constexpr InputCode INPUT_SCANCODE_F14 = INPUT_KEYBOARD_OFFSET + 105;
constexpr InputCode INPUT_SCANCODE_F15 = INPUT_KEYBOARD_OFFSET + 106;
constexpr InputCode INPUT_SCANCODE_F16 = INPUT_KEYBOARD_OFFSET + 107;
constexpr InputCode INPUT_SCANCODE_F17 = INPUT_KEYBOARD_OFFSET + 108;
constexpr InputCode INPUT_SCANCODE_F18 = INPUT_KEYBOARD_OFFSET + 109;
constexpr InputCode INPUT_SCANCODE_F19 = INPUT_KEYBOARD_OFFSET + 110;
constexpr InputCode INPUT_SCANCODE_F20 = INPUT_KEYBOARD_OFFSET + 111;
constexpr InputCode INPUT_SCANCODE_F21 = INPUT_KEYBOARD_OFFSET + 112;
constexpr InputCode INPUT_SCANCODE_F22 = INPUT_KEYBOARD_OFFSET + 113;
constexpr InputCode INPUT_SCANCODE_F23 = INPUT_KEYBOARD_OFFSET + 114;
constexpr InputCode INPUT_SCANCODE_F24 = INPUT_KEYBOARD_OFFSET + 115;
constexpr InputCode INPUT_SCANCODE_EXECUTE = INPUT_KEYBOARD_OFFSET + 116;
constexpr InputCode INPUT_SCANCODE_HELP = INPUT_KEYBOARD_OFFSET + 117;
constexpr InputCode INPUT_SCANCODE_MENU = INPUT_KEYBOARD_OFFSET + 118;
constexpr InputCode INPUT_SCANCODE_SELECT = INPUT_KEYBOARD_OFFSET + 119;
constexpr InputCode INPUT_SCANCODE_STOP = INPUT_KEYBOARD_OFFSET + 120;
constexpr InputCode INPUT_SCANCODE_AGAIN = INPUT_KEYBOARD_OFFSET + 121;
constexpr InputCode INPUT_SCANCODE_UNDO = INPUT_KEYBOARD_OFFSET + 122;
constexpr InputCode INPUT_SCANCODE_CUT = INPUT_KEYBOARD_OFFSET + 123;
constexpr InputCode INPUT_SCANCODE_COPY = INPUT_KEYBOARD_OFFSET + 124;
constexpr InputCode INPUT_SCANCODE_PASTE = INPUT_KEYBOARD_OFFSET + 125;
constexpr InputCode INPUT_SCANCODE_FIND = INPUT_KEYBOARD_OFFSET + 126;
constexpr InputCode INPUT_SCANCODE_MUTE = INPUT_KEYBOARD_OFFSET + 127;
constexpr InputCode INPUT_SCANCODE_VOLUMEUP = INPUT_KEYBOARD_OFFSET + 128;
constexpr InputCode INPUT_SCANCODE_VOLUMEDOWN = INPUT_KEYBOARD_OFFSET + 129;
// not sure whether there's a reason to enable these
// constexpr InputCode INPUT_SCANCODE_LOCKINGCAPSLOCK = INPUT_KEYBOARD_OFFSET + 130;
// constexpr InputCode INPUT_SCANCODE_LOCKINGNUMLOCK = INPUT_KEYBOARD_OFFSET + 131;
// constexpr InputCode INPUT_SCANCODE_LOCKINGSCROLLLOCK = INPUT_KEYBOARD_OFFSET + 132;
constexpr InputCode INPUT_SCANCODE_KP_COMMA = INPUT_KEYBOARD_OFFSET + 133;
constexpr InputCode INPUT_SCANCODE_KP_EQUALSAS400 = INPUT_KEYBOARD_OFFSET + 134;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL1 = INPUT_KEYBOARD_OFFSET + 135;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL2 = INPUT_KEYBOARD_OFFSET + 136;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL3 = INPUT_KEYBOARD_OFFSET + 137;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL4 = INPUT_KEYBOARD_OFFSET + 138;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL5 = INPUT_KEYBOARD_OFFSET + 139;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL6 = INPUT_KEYBOARD_OFFSET + 140;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL7 = INPUT_KEYBOARD_OFFSET + 141;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL8 = INPUT_KEYBOARD_OFFSET + 142;
constexpr InputCode INPUT_SCANCODE_INTERNATIONAL9 = INPUT_KEYBOARD_OFFSET + 143;
constexpr InputCode INPUT_SCANCODE_LANG1 = INPUT_KEYBOARD_OFFSET + 144; // Hangul/English toggle
constexpr InputCode INPUT_SCANCODE_LANG2 = INPUT_KEYBOARD_OFFSET + 145; // Hanja conversion
constexpr InputCode INPUT_SCANCODE_LANG3 = INPUT_KEYBOARD_OFFSET + 146; // Katakana
constexpr InputCode INPUT_SCANCODE_LANG4 = INPUT_KEYBOARD_OFFSET + 147; // Hiragana
constexpr InputCode INPUT_SCANCODE_LANG5 = INPUT_KEYBOARD_OFFSET + 148; // Zenkaku/Hankaku
constexpr InputCode INPUT_SCANCODE_LANG6 = INPUT_KEYBOARD_OFFSET + 149; // reserved
constexpr InputCode INPUT_SCANCODE_LANG7 = INPUT_KEYBOARD_OFFSET + 150; // reserved
constexpr InputCode INPUT_SCANCODE_LANG8 = INPUT_KEYBOARD_OFFSET + 151; // reserved
constexpr InputCode INPUT_SCANCODE_LANG9 = INPUT_KEYBOARD_OFFSET + 152; // reserved
constexpr InputCode INPUT_SCANCODE_ALTERASE = INPUT_KEYBOARD_OFFSET + 153;
constexpr InputCode INPUT_SCANCODE_SYSREQ = INPUT_KEYBOARD_OFFSET + 154;
constexpr InputCode INPUT_SCANCODE_CANCEL = INPUT_KEYBOARD_OFFSET + 155;
constexpr InputCode INPUT_SCANCODE_CLEAR = INPUT_KEYBOARD_OFFSET + 156;
constexpr InputCode INPUT_SCANCODE_PRIOR = INPUT_KEYBOARD_OFFSET + 157;
constexpr InputCode INPUT_SCANCODE_RETURN2 = INPUT_KEYBOARD_OFFSET + 158;
constexpr InputCode INPUT_SCANCODE_SEPARATOR = INPUT_KEYBOARD_OFFSET + 159;
constexpr InputCode INPUT_SCANCODE_OUT = INPUT_KEYBOARD_OFFSET + 160;
constexpr InputCode INPUT_SCANCODE_OPER = INPUT_KEYBOARD_OFFSET + 161;
constexpr InputCode INPUT_SCANCODE_CLEARAGAIN = INPUT_KEYBOARD_OFFSET + 162;
constexpr InputCode INPUT_SCANCODE_CRSEL = INPUT_KEYBOARD_OFFSET + 163;
constexpr InputCode INPUT_SCANCODE_EXSEL = INPUT_KEYBOARD_OFFSET + 164;
constexpr InputCode INPUT_SCANCODE_KP_00 = INPUT_KEYBOARD_OFFSET + 176;
constexpr InputCode INPUT_SCANCODE_KP_000 = INPUT_KEYBOARD_OFFSET + 177;
constexpr InputCode INPUT_SCANCODE_THOUSANDSSEPARATOR = INPUT_KEYBOARD_OFFSET + 178;
constexpr InputCode INPUT_SCANCODE_DECIMALSEPARATOR = INPUT_KEYBOARD_OFFSET + 179;
constexpr InputCode INPUT_SCANCODE_CURRENCYUNIT = INPUT_KEYBOARD_OFFSET + 180;
constexpr InputCode INPUT_SCANCODE_CURRENCYSUBUNIT = INPUT_KEYBOARD_OFFSET + 181;
constexpr InputCode INPUT_SCANCODE_KP_LEFTPAREN = INPUT_KEYBOARD_OFFSET + 182;
constexpr InputCode INPUT_SCANCODE_KP_RIGHTPAREN = INPUT_KEYBOARD_OFFSET + 183;
constexpr InputCode INPUT_SCANCODE_KP_LEFTBRACE = INPUT_KEYBOARD_OFFSET + 184;
constexpr InputCode INPUT_SCANCODE_KP_RIGHTBRACE = INPUT_KEYBOARD_OFFSET + 185;
constexpr InputCode INPUT_SCANCODE_KP_TAB = INPUT_KEYBOARD_OFFSET + 186;
constexpr InputCode INPUT_SCANCODE_KP_BACKSPACE = INPUT_KEYBOARD_OFFSET + 187;
constexpr InputCode INPUT_SCANCODE_KP_A = INPUT_KEYBOARD_OFFSET + 188;
constexpr InputCode INPUT_SCANCODE_KP_B = INPUT_KEYBOARD_OFFSET + 189;
constexpr InputCode INPUT_SCANCODE_KP_C = INPUT_KEYBOARD_OFFSET + 190;
constexpr InputCode INPUT_SCANCODE_KP_D = INPUT_KEYBOARD_OFFSET + 191;
constexpr InputCode INPUT_SCANCODE_KP_E = INPUT_KEYBOARD_OFFSET + 192;
constexpr InputCode INPUT_SCANCODE_KP_F = INPUT_KEYBOARD_OFFSET + 193;
constexpr InputCode INPUT_SCANCODE_KP_XOR = INPUT_KEYBOARD_OFFSET + 194;
constexpr InputCode INPUT_SCANCODE_KP_POWER = INPUT_KEYBOARD_OFFSET + 195;
constexpr InputCode INPUT_SCANCODE_KP_PERCENT = INPUT_KEYBOARD_OFFSET + 196;
constexpr InputCode INPUT_SCANCODE_KP_LESS = INPUT_KEYBOARD_OFFSET + 197;
constexpr InputCode INPUT_SCANCODE_KP_GREATER = INPUT_KEYBOARD_OFFSET + 198;
constexpr InputCode INPUT_SCANCODE_KP_AMPERSAND = INPUT_KEYBOARD_OFFSET + 199;
constexpr InputCode INPUT_SCANCODE_KP_DBLAMPERSAND = INPUT_KEYBOARD_OFFSET + 200;
constexpr InputCode INPUT_SCANCODE_KP_VERTICALBAR = INPUT_KEYBOARD_OFFSET + 201;
constexpr InputCode INPUT_SCANCODE_KP_DBLVERTICALBAR = INPUT_KEYBOARD_OFFSET + 202;
constexpr InputCode INPUT_SCANCODE_KP_COLON = INPUT_KEYBOARD_OFFSET + 203;
constexpr InputCode INPUT_SCANCODE_KP_HASH = INPUT_KEYBOARD_OFFSET + 204;
constexpr InputCode INPUT_SCANCODE_KP_SPACE = INPUT_KEYBOARD_OFFSET + 205;
constexpr InputCode INPUT_SCANCODE_KP_AT = INPUT_KEYBOARD_OFFSET + 206;
constexpr InputCode INPUT_SCANCODE_KP_EXCLAM = INPUT_KEYBOARD_OFFSET + 207;
constexpr InputCode INPUT_SCANCODE_KP_MEMSTORE = INPUT_KEYBOARD_OFFSET + 208;
constexpr InputCode INPUT_SCANCODE_KP_MEMRECALL = INPUT_KEYBOARD_OFFSET + 209;
constexpr InputCode INPUT_SCANCODE_KP_MEMCLEAR = INPUT_KEYBOARD_OFFSET + 210;
constexpr InputCode INPUT_SCANCODE_KP_MEMADD = INPUT_KEYBOARD_OFFSET + 211;
constexpr InputCode INPUT_SCANCODE_KP_MEMSUBTRACT = INPUT_KEYBOARD_OFFSET + 212;
constexpr InputCode INPUT_SCANCODE_KP_MEMMULTIPLY = INPUT_KEYBOARD_OFFSET + 213;
constexpr InputCode INPUT_SCANCODE_KP_MEMDIVIDE = INPUT_KEYBOARD_OFFSET + 214;
constexpr InputCode INPUT_SCANCODE_KP_PLUSMINUS = INPUT_KEYBOARD_OFFSET + 215;
constexpr InputCode INPUT_SCANCODE_KP_CLEAR = INPUT_KEYBOARD_OFFSET + 216;
constexpr InputCode INPUT_SCANCODE_KP_CLEARENTRY = INPUT_KEYBOARD_OFFSET + 217;
constexpr InputCode INPUT_SCANCODE_KP_BINARY = INPUT_KEYBOARD_OFFSET + 218;
constexpr InputCode INPUT_SCANCODE_KP_OCTAL = INPUT_KEYBOARD_OFFSET + 219;
constexpr InputCode INPUT_SCANCODE_KP_DECIMAL = INPUT_KEYBOARD_OFFSET + 220;
constexpr InputCode INPUT_SCANCODE_KP_HEXADECIMAL = INPUT_KEYBOARD_OFFSET + 221;
constexpr InputCode INPUT_SCANCODE_LCTRL = INPUT_KEYBOARD_OFFSET + 224;
constexpr InputCode INPUT_SCANCODE_LSHIFT = INPUT_KEYBOARD_OFFSET + 225;
constexpr InputCode INPUT_SCANCODE_LALT = INPUT_KEYBOARD_OFFSET + 226;
constexpr InputCode INPUT_SCANCODE_LGUI = INPUT_KEYBOARD_OFFSET + 227;
constexpr InputCode INPUT_SCANCODE_RCTRL = INPUT_KEYBOARD_OFFSET + 228;
constexpr InputCode INPUT_SCANCODE_RSHIFT = INPUT_KEYBOARD_OFFSET + 229;
constexpr InputCode INPUT_SCANCODE_RALT = INPUT_KEYBOARD_OFFSET + 230;
constexpr InputCode INPUT_SCANCODE_RGUI = INPUT_KEYBOARD_OFFSET + 231;
constexpr InputCode INPUT_SCANCODE_MODE = INPUT_KEYBOARD_OFFSET + 257;
constexpr InputCode INPUT_SCANCODE_AUDIONEXT = INPUT_KEYBOARD_OFFSET + 258;
constexpr InputCode INPUT_SCANCODE_AUDIOPREV = INPUT_KEYBOARD_OFFSET + 259;
constexpr InputCode INPUT_SCANCODE_AUDIOSTOP = INPUT_KEYBOARD_OFFSET + 260;
constexpr InputCode INPUT_SCANCODE_AUDIOPLAY = INPUT_KEYBOARD_OFFSET + 261;
constexpr InputCode INPUT_SCANCODE_AUDIOMUTE = INPUT_KEYBOARD_OFFSET + 262;
constexpr InputCode INPUT_SCANCODE_MEDIASELECT = INPUT_KEYBOARD_OFFSET + 263;
constexpr InputCode INPUT_SCANCODE_WWW = INPUT_KEYBOARD_OFFSET + 264;
constexpr InputCode INPUT_SCANCODE_MAIL = INPUT_KEYBOARD_OFFSET + 265;
constexpr InputCode INPUT_SCANCODE_CALCULATOR = INPUT_KEYBOARD_OFFSET + 266;
constexpr InputCode INPUT_SCANCODE_COMPUTER = INPUT_KEYBOARD_OFFSET + 267;
constexpr InputCode INPUT_SCANCODE_AC_SEARCH = INPUT_KEYBOARD_OFFSET + 268;
constexpr InputCode INPUT_SCANCODE_AC_HOME = INPUT_KEYBOARD_OFFSET + 269;
constexpr InputCode INPUT_SCANCODE_AC_BACK = INPUT_KEYBOARD_OFFSET + 270;
constexpr InputCode INPUT_SCANCODE_AC_FORWARD = INPUT_KEYBOARD_OFFSET + 271;
constexpr InputCode INPUT_SCANCODE_AC_STOP = INPUT_KEYBOARD_OFFSET + 272;
constexpr InputCode INPUT_SCANCODE_AC_REFRESH = INPUT_KEYBOARD_OFFSET + 273;
constexpr InputCode INPUT_SCANCODE_AC_BOOKMARKS = INPUT_KEYBOARD_OFFSET + 274;
constexpr InputCode INPUT_SCANCODE_BRIGHTNESSDOWN = INPUT_KEYBOARD_OFFSET + 275;
constexpr InputCode INPUT_SCANCODE_BRIGHTNESSUP = INPUT_KEYBOARD_OFFSET + 276;
constexpr InputCode INPUT_SCANCODE_DISPLAYSWITCH = INPUT_KEYBOARD_OFFSET + 277;
constexpr InputCode INPUT_SCANCODE_KBDILLUMTOGGLE = INPUT_KEYBOARD_OFFSET + 278;
constexpr InputCode INPUT_SCANCODE_KBDILLUMDOWN = INPUT_KEYBOARD_OFFSET + 279;
constexpr InputCode INPUT_SCANCODE_KBDILLUMUP = INPUT_KEYBOARD_OFFSET + 280;
constexpr InputCode INPUT_SCANCODE_EJECT = INPUT_KEYBOARD_OFFSET + 281;
constexpr InputCode INPUT_SCANCODE_SLEEP = INPUT_KEYBOARD_OFFSET + 282;
constexpr InputCode INPUT_SCANCODE_APP1 = INPUT_KEYBOARD_OFFSET + 283;
constexpr InputCode INPUT_SCANCODE_APP2 = INPUT_KEYBOARD_OFFSET + 284;
constexpr InputCode INPUT_SCANCODE_AUDIOREWIND = INPUT_KEYBOARD_OFFSET + 285;
constexpr InputCode INPUT_SCANCODE_AUDIOFASTFORWARD = INPUT_KEYBOARD_OFFSET + 286;
constexpr InputCode INPUT_SCANCODE_SOFTLEFT = INPUT_KEYBOARD_OFFSET + 287;
constexpr InputCode INPUT_SCANCODE_SOFTRIGHT = INPUT_KEYBOARD_OFFSET + 288;
constexpr InputCode INPUT_SCANCODE_CALL = INPUT_KEYBOARD_OFFSET + 289;
constexpr InputCode INPUT_SCANCODE_ENDCALL = INPUT_KEYBOARD_OFFSET + 290;

// Mouse input
// Base from SDL_mouse.h
// https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_mouse.h#L462
constexpr InputCode INPUT_MOUSE_BUTTON_LEFT = INPUT_MOUSE_OFFSET + 1;
constexpr InputCode INPUT_MOUSE_BUTTON_MIDDLE = INPUT_MOUSE_OFFSET + 2;
constexpr InputCode INPUT_MOUSE_BUTTON_RIGHT = INPUT_MOUSE_OFFSET + 3;
constexpr InputCode INPUT_MOUSE_BUTTON_X1 = INPUT_MOUSE_OFFSET + 4;
constexpr InputCode INPUT_MOUSE_BUTTON_X2 = INPUT_MOUSE_OFFSET + 5;

// Controller 1 input
// Base from SDL_gamepad.h
// https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_gamepad.h#L85C1-L106C1
constexpr InputCode CONTROLLER1_BUTTON_A = INPUT_CONTROLLER1_OFFSET + 1;
constexpr InputCode CONTROLLER1_BUTTON_B = INPUT_CONTROLLER1_OFFSET + 2;
constexpr InputCode CONTROLLER1_BUTTON_X = INPUT_CONTROLLER1_OFFSET + 3;
constexpr InputCode CONTROLLER1_BUTTON_Y = INPUT_CONTROLLER1_OFFSET + 4;
constexpr InputCode CONTROLLER1_BUTTON_BACK = INPUT_CONTROLLER1_OFFSET + 5;
constexpr InputCode CONTROLLER1_BUTTON_GUIDE = INPUT_CONTROLLER1_OFFSET + 6;
constexpr InputCode CONTROLLER1_BUTTON_START = INPUT_CONTROLLER1_OFFSET + 7;
constexpr InputCode CONTROLLER1_BUTTON_LEFT_STICK = INPUT_CONTROLLER1_OFFSET + 8;
constexpr InputCode CONTROLLER1_BUTTON_RIGHT_STICK = INPUT_CONTROLLER1_OFFSET + 9;
constexpr InputCode CONTROLLER1_BUTTON_LEFT_SHOULDER = INPUT_CONTROLLER1_OFFSET + 10;
constexpr InputCode CONTROLLER1_BUTTON_RIGHT_SHOULDER = INPUT_CONTROLLER1_OFFSET + 11;
constexpr InputCode CONTROLLER1_BUTTON_DPAD_UP = INPUT_CONTROLLER1_OFFSET + 12;
constexpr InputCode CONTROLLER1_BUTTON_DPAD_DOWN = INPUT_CONTROLLER1_OFFSET + 13;
constexpr InputCode CONTROLLER1_BUTTON_DPAD_LEFT = INPUT_CONTROLLER1_OFFSET + 14;
constexpr InputCode CONTROLLER1_BUTTON_DPAD_RIGHT = INPUT_CONTROLLER1_OFFSET + 15;
constexpr InputCode CONTROLLER1_BUTTON_MISC1 = INPUT_CONTROLLER1_OFFSET + 16;    // Xbox Series X share button PS5 microphone button Nintendo Switch Pro capture button Amazon Luna microphone button
constexpr InputCode CONTROLLER1_BUTTON_PADDLE1 = INPUT_CONTROLLER1_OFFSET + 17;  // Xbox Elite paddle P1 (upper left facing the back)
constexpr InputCode CONTROLLER1_BUTTON_PADDLE2 = INPUT_CONTROLLER1_OFFSET + 18;  // Xbox Elite paddle P3 (upper right facing the back)
constexpr InputCode CONTROLLER1_BUTTON_PADDLE3 = INPUT_CONTROLLER1_OFFSET + 19;  // Xbox Elite paddle P2 (lower left facing the back)
constexpr InputCode CONTROLLER1_BUTTON_PADDLE4 = INPUT_CONTROLLER1_OFFSET + 20;  // Xbox Elite paddle P4 (lower right facing the back)
constexpr InputCode CONTROLLER1_BUTTON_TOUCHPAD = INPUT_CONTROLLER1_OFFSET + 21; // PS4/PS5 touchpad button

constexpr InputCode INPUT_LAST = CONTROLLER1_BUTTON_TOUCHPAD + 1;

// Controller axis
// Based from SDL_gamepad.h
// https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_gamepad.h#L121
constexpr InputCode CONTROLLER_AXIS_LEFTX = 0;
constexpr InputCode CONTROLLER_AXIS_LEFTY = 1;
constexpr InputCode CONTROLLER_AXIS_RIGHTX = 2;
constexpr InputCode CONTROLLER_AXIS_RIGHTY = 3;
constexpr InputCode CONTROLLER_AXIS_LEFT_TRIGGER = 4;
constexpr InputCode CONTROLLER_AXIS_RIGHT_TRIGGER = 5;

enum class InputSource {
    Unknown = 1,
    Keyboard,
    Mouse,
    Controller,
};

enum class InputAction {
    Unknown = 1,
    Pressed,
    Released,
    Moved,
};

struct InputEvent {
    InputSource source = InputSource::Unknown;
    InputAction action = InputAction::Unknown;
    InputCode code = INPUT_CODE_NONE;
};

NomadString getInputCodeName(InputCode code);
InputCode getInputCode(const NomadString& name);

void mapSdlKeyboardEvent(SDL_KeyboardEvent& event, InputEvent& inputEvent);
void mapSdlMouseEvent(SDL_MouseButtonEvent& event, InputEvent& inputEvent);
void mapSdlGamepadButtonEvent(SDL_GamepadButtonEvent& event, InputEvent& inputEvent);
void mapSdlGamepadAxisEvent(SDL_GamepadAxisEvent& event, InputEvent& input_event);

} // nomad
