if(NOT DEFINED NOMAD_RUNTIME OR NOT DEFINED NOMAD_RUNTIME_DESTINATION)
    message(FATAL_ERROR "NOMAD_RUNTIME and NOMAD_RUNTIME_DESTINATION are required")
endif()

file(
    GET_RUNTIME_DEPENDENCIES
    EXECUTABLES "${NOMAD_RUNTIME}"
    RESOLVED_DEPENDENCIES_VAR NOMAD_RUNTIME_DEPENDENCIES
    UNRESOLVED_DEPENDENCIES_VAR NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES
    POST_EXCLUDE_REGEXES
        "^/lib/"
        "^/lib64/"
        "^/usr/lib/"
        "^/System/Library/"
)

if(NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES)
    list(JOIN NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES ", " NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES_TEXT)
    message(FATAL_ERROR "Unresolved Nomad runtime dependencies: ${NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES_TEXT}")
endif()

foreach(NOMAD_RUNTIME_DEPENDENCY IN LISTS NOMAD_RUNTIME_DEPENDENCIES)
    get_filename_component(NOMAD_RUNTIME_DEPENDENCY_NAME "${NOMAD_RUNTIME_DEPENDENCY}" NAME)
    file(
        COPY_FILE
        "${NOMAD_RUNTIME_DEPENDENCY}"
        "${NOMAD_RUNTIME_DESTINATION}/${NOMAD_RUNTIME_DEPENDENCY_NAME}"
    )
endforeach()
