if(NOT DEFINED NOMAD_RUNTIME_DESTINATION)
    message(FATAL_ERROR "NOMAD_RUNTIME_DESTINATION is required")
endif()

file(MAKE_DIRECTORY "${NOMAD_RUNTIME_DESTINATION}")

if(DEFINED NOMAD_RUNTIME AND NOT NOMAD_RUNTIME STREQUAL "")
    get_filename_component(NOMAD_RUNTIME_NAME "${NOMAD_RUNTIME}" NAME)
    file(
        COPY_FILE
        "${NOMAD_RUNTIME}"
        "${NOMAD_RUNTIME_DESTINATION}/${NOMAD_RUNTIME_NAME}"
        ONLY_IF_DIFFERENT
    )
endif()

if(DEFINED NOMAD_RUNTIME_DEPENDENCIES)
    string(REPLACE "|" ";" NOMAD_RUNTIME_DEPENDENCIES "${NOMAD_RUNTIME_DEPENDENCIES}")
elseif(DEFINED NOMAD_RUNTIME AND NOT NOMAD_RUNTIME STREQUAL "")
    file(
        GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${NOMAD_RUNTIME}"
        RESOLVED_DEPENDENCIES_VAR NOMAD_RUNTIME_DEPENDENCIES
        UNRESOLVED_DEPENDENCIES_VAR NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES
        POST_EXCLUDE_REGEXES
            "^/lib/"
            "^/lib64/"
            "^/usr/lib/"
            "^/System/Library/"
    )

    if(NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES)
        list(JOIN NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES ", " NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES_TEXT)
        message(FATAL_ERROR "Unresolved Nomad runtime dependencies: ${NOMAD_UNRESOLVED_RUNTIME_DEPENDENCIES_TEXT}")
    endif()
else()
    message(FATAL_ERROR "NOMAD_RUNTIME or NOMAD_RUNTIME_DEPENDENCIES is required")
endif()

foreach(NOMAD_RUNTIME_DEPENDENCY IN LISTS NOMAD_RUNTIME_DEPENDENCIES)
    get_filename_component(NOMAD_RUNTIME_DEPENDENCY_NAME "${NOMAD_RUNTIME_DEPENDENCY}" NAME)
    set(NOMAD_RUNTIME_DEPENDENCY_DESTINATION
        "${NOMAD_RUNTIME_DESTINATION}/${NOMAD_RUNTIME_DEPENDENCY_NAME}"
    )

    if("${NOMAD_RUNTIME_DEPENDENCY}" STREQUAL "${NOMAD_RUNTIME_DEPENDENCY_DESTINATION}")
        continue()
    endif()

    file(
        COPY_FILE
        "${NOMAD_RUNTIME_DEPENDENCY}"
        "${NOMAD_RUNTIME_DEPENDENCY_DESTINATION}"
        ONLY_IF_DIFFERENT
    )
endforeach()
