if(NOT DEFINED NOMAD_DOCUMENTATION_SDK)
    message(FATAL_ERROR "NOMAD_DOCUMENTATION_SDK must name an extracted SDK directory")
endif()
get_filename_component(NOMAD_DOCUMENTATION_SDK "${NOMAD_DOCUMENTATION_SDK}" ABSOLUTE)
get_filename_component(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(OUTPUT "${SOURCE_ROOT}/out/documentation")
set(PROJECT "${OUTPUT}/project")
if(CMAKE_HOST_WIN32)
    set(SUFFIX ".exe")
else()
    set(SUFFIX "")
endif()
foreach(PROGRAM IN ITEMS nomad nomadc)
    if(NOT EXISTS "${NOMAD_DOCUMENTATION_SDK}/${PROGRAM}${SUFFIX}")
        message(FATAL_ERROR "Missing SDK tool: ${NOMAD_DOCUMENTATION_SDK}/${PROGRAM}${SUFFIX}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}/source")
file(COPY "${SOURCE_ROOT}/docs/" DESTINATION "${OUTPUT}/source"
    FILES_MATCHING PATTERN "*.md" PATTERN "releases.md" EXCLUDE)
if(EXISTS "${PROJECT}")
    file(REMOVE_RECURSE "${PROJECT}")
endif()
function(run_documentation_command)
    execute_process(COMMAND ${ARGV}
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE COMMAND_OUTPUT ERROR_VARIABLE COMMAND_ERROR TIMEOUT 60)
    if(NOT RESULT STREQUAL "0")
        message(FATAL_ERROR "Documentation command failed (${RESULT}): ${ARGV}\n${COMMAND_OUTPUT}\n${COMMAND_ERROR}")
    endif()
endfunction()
run_documentation_command("${NOMAD_DOCUMENTATION_SDK}/nomad${SUFFIX}" init "${PROJECT}")
run_documentation_command("${NOMAD_DOCUMENTATION_SDK}/nomadc${SUFFIX}" docs "${PROJECT}"
    --output "${OUTPUT}/source/engine-api.md")
file(SIZE "${OUTPUT}/source/engine-api.md" API_SIZE)
if(API_SIZE EQUAL 0)
    message(FATAL_ERROR "Generated engine API documentation is empty")
endif()
file(REMOVE_RECURSE "${PROJECT}")
message(STATUS "Documentation source prepared in ${OUTPUT}/source")
