if(NOT TARGET nomad-cli OR NOT TARGET nomadc OR NOT TARGET nomad-runtime OR NOMAD_ENABLE_SANITIZERS)
    return()
endif()

foreach(PROGRAM IN ITEMS nomad-cli nomadc)
    if(APPLE)
        set_target_properties(${PROGRAM} PROPERTIES BUILD_RPATH "@loader_path")
    elseif(UNIX)
        set_target_properties(${PROGRAM} PROPERTIES BUILD_RPATH "$ORIGIN" BUILD_RPATH_USE_ORIGIN TRUE)
    endif()
endforeach()

set(NOMAD_DISTRIBUTION_CONFIG "${CMAKE_CURRENT_BINARY_DIR}/Distribution-$<CONFIG>.cmake")
set(NOMAD_DISTRIBUTION_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/distribution/$<CONFIG>")
set(NOMAD_DISTRIBUTION_SETTINGS
    "set(NOMAD_DISTRIBUTION_VERSION \"${PROJECT_VERSION}\")\n"
    "set(NOMAD_DISTRIBUTION_PLATFORM \"${NOMAD_PACKAGE_PLATFORM}\")\n"
    "set(NOMAD_DISTRIBUTION_OUTPUT \"${NOMAD_DISTRIBUTION_OUTPUT}\")\n"
    "set(NOMAD_DISTRIBUTION_CLI \"$<TARGET_FILE:nomad-cli>\")\n"
    "set(NOMAD_DISTRIBUTION_COMPILER \"$<TARGET_FILE:nomadc>\")\n"
    "set(NOMAD_DISTRIBUTION_RUNTIME \"$<TARGET_FILE:nomad-runtime>\")\n"
    "set(NOMAD_DISTRIBUTION_BUNDLE \"$<TARGET_FILE_DIR:nomad-runtime>/runtime\")\n"
    "set(NOMAD_DISTRIBUTION_TEMPLATES \"${NOMAD_PROJECT_TEMPLATE_DIR}\")\n"
    "set(NOMAD_DISTRIBUTION_DOCUMENTATION \"${CMAKE_CURRENT_SOURCE_DIR}/docs/language.md\")\n"
)
if(WIN32)
    list(APPEND NOMAD_DISTRIBUTION_SETTINGS
        "set(NOMAD_DISTRIBUTION_CLI_DLLS \"$<JOIN:$<TARGET_RUNTIME_DLLS:nomad-cli>,|>\")\n"
        "set(NOMAD_DISTRIBUTION_COMPILER_DLLS \"$<JOIN:$<TARGET_RUNTIME_DLLS:nomadc>,|>\")\n"
        "set(NOMAD_DISTRIBUTION_RUNTIME_DLLS \"$<JOIN:$<TARGET_RUNTIME_DLLS:nomad-runtime>,|>\")\n"
    )
endif()
list(JOIN NOMAD_DISTRIBUTION_SETTINGS "" NOMAD_DISTRIBUTION_SETTINGS)
file(GENERATE OUTPUT "${NOMAD_DISTRIBUTION_CONFIG}" CONTENT "${NOMAD_DISTRIBUTION_SETTINGS}")

add_custom_target(nomad-distribution
    COMMAND "${CMAKE_COMMAND}" "-DNOMAD_DISTRIBUTION_CONFIG=${NOMAD_DISTRIBUTION_CONFIG}"
        -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/CreateDistribution.cmake"
    DEPENDS nomad-cli nomadc nomad-runtime-bundle
    VERBATIM
)
